apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaf-s3-connector.fullname" . }}
spec:
  selector:
    app: {{ include "kaf-s3-connector.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: metrics
